name: Remove AWS Robomaker resources.

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  remove_docker_images:
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/remove_docker_images.yml
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  remove_robomaker_simulations:
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/remove_robomaker_simulations.yml
    secrets:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
