name: Remove AWS Robomaker resources

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY:
        required: true
      AWS_ECR_REPOSITORY:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  remove_docker_image:
    runs-on: ubuntu-22.04
    name: Remove AWS Robomaker resources

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Remove docker image to Amazon ECR
        env:
          IMAGE_TAG: PR-${{ github.event.number }}
          REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        run: |
          ./docker/remove_image_ci.sh -i $IMAGE_TAG -r $REPOSITORY